services:
  db: 
    image: postgres:16.0-alpine3.18
    environment:
      - POSTGRES_DB=postgres_db
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password

  advert-app:
    build: 
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
    environment:
      - DB_HOST=db
      - DB_NAME=postgres_db
      - DB_USER=postgres_user
      - DB_PASSWORD=postgres_password
    command: >
      sh -c "sleep 10 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
